### ISSUE TITLE
cec-web not compatible with libcec3 and RPi3

### ISSUE THREAD

**Issue by eriksmets** [robbiet480/cec-web#3]
Hi. 

I've been using cec-web for over a year now, and I've recently replaced my pi with a new model (rpi 3). 
However I can't get libcec2 to run on the device. I've used libcec3 and chbmuc/cec (which was updated recently) to run his simple program, so I know libcec3 works.

However, I can't seem to get a version of cec-web to work with libcec3. Any chance you could help me ?

`# github.com/robbiet480/cec`
`could not determine kind of name for C.cec_get_device_physical_address`

Thanks in advance.

**Comment by eriksmets** [comment]
Update:

I was able to compile cec-web with old versions of libcec2 and libcec-dev. 
`
dpkg -r libcec3 libcec-dev;
apt-get install libcec-dev=2.1.4-2 libcec2=2.1.4-2;
cd cec-web;
go build`

However, this version does not work on RPi3/Jessie.
So you have to update to libcec2-2.2.0.
(This forces an upgrade of libcec-dev, and blocks compiling again)

But it's a workaround for me.

**Comment by robbiet480** [comment]
@eriksmets Will take a look at this this weekend, but compatibility will mostly depend on the upstream Go library I use for talking to libcec, @chbmuc's [cec.go](https://github.com/chbmuc/cec).

**Comment by robbiet480** [comment]
@eriksmets Just a quick update to let you know I did get a chance to look at cec.go over the weekend and think I got it updated to work with cec-web without needing to do a lot of work on it. I should get the cec-web stuff done this week.

**Comment by eriksmets** [comment]
Hi,

Compiling the v2 branch of cec-web works, but it panics when I make requests.

2016/08/01 15:09:38 [Recovery] panic recovered:
GET /info HTTP/1.1
Host: 192.168.8.212:8080
Accept: _/_
User-Agent: curl/7.43.0

runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:443 (0x45f6c)
    gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:62 (0x4463c)
    panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x5c0d0)
    sigpanic: panicmem()
/usr/local/go/packages/src/github.com/robbiet480/cec/libcec.go:242 (0x1062a8)
    (_Connection).GetActiveDevices: result := C.libcec_get_active_devices(c.connection)
/usr/local/go/packages/src/github.com/robbiet480/cec/cec.go:151 (0x101e7c)
    (_Connection).List: activeDevices := c.GetActiveDevices()
/root/projectsDL/cec-web/cec-web.go:166 (0x14984)
    info: list := cec_conn.List()
/usr/local/go/packages/src/github.com/gin-gonic/gin/context.go:97 (0xd03a0)
    (_Context).Next: c.handlers[c.index](c)
/usr/local/go/packages/src/github.com/gin-gonic/gin/logger.go:30 (0xdfcac)
    ErrorLoggerT.func1: c.Next()
/usr/local/go/packages/src/github.com/gin-gonic/gin/context.go:97 (0xd03a0)
    (_Context).Next: c.handlers[c.index](c)
/usr/local/go/packages/src/github.com/gin-gonic/gin/recovery.go:45 (0xe0894)
    RecoveryWithWriter.func1: c.Next()
/usr/local/go/packages/src/github.com/gin-gonic/gin/context.go:97 (0xd03a0)
    (_Context).Next: c.handlers[c.index](c)
/usr/local/go/packages/src/github.com/gin-gonic/gin/logger.go:63 (0xdfe0c)
    LoggerWithWriter.func1: c.Next()
/usr/local/go/packages/src/github.com/gin-gonic/gin/context.go:97 (0xd03a0)
    (_Context).Next: c.handlers[c.index](c)
/usr/local/go/packages/src/github.com/gin-gonic/gin/gin.go:284 (0xd63e0)
    (_Engine).handleHTTPRequest: context.Next()
/usr/local/go/packages/src/github.com/gin-gonic/gin/gin.go:265 (0xd60ec)
    (_Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2081 (0x1f2ad0)
    serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1472 (0x1efa28)
    (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_arm.s:990 (0x75a88)
    goexit: MOVW    R0, R0  // NOP

**Comment by robbiet480** [comment]
@eriksmets I'm aware of that, the branches still need more work which I plan to complete in the next month. Sorry for the delay!

**Comment by eriksmets** [comment]
Wasn't trying to pressure you, just making sure you are aware. Thx

**Comment by robbiet480** [comment]
@eriksmets Okay when I said month I really meant like... 3 months.

cec-web and cec are now libcec3 compatible! I can't speak for the RPi3 though since I don't have one, so you will have to let me know.

Closing this, reopen if you still have issues.

Sorry for the delay!
